repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: python test.py
        language: system
        pass_filenames: false
        stages: [push]
