repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Typing
        args: ["--config-file=mypy.ini"]
  - repo: local
    hooks:
      - id: run-tests
        name: Tests
        entry: python test.py
        language: system
        pass_filenames: false
        stages: [pre-push]

# pre-commit install --hook-type pre-commit
# pre-commit install --hook-type pre-push
